# Ben Rudinski
# SoftDev
# September 2024

from flask import Flask
app = Flask(__name__)          # ...

@app.route("/")                # ...
def hello_world():
    print(__name__)            # ...
    return "No hablo queso!"   # ...

app.run()                      # ...

# We predicted this one would run the link and it did that.
