# College Teams Ranking Program

# This program creates a ranking for all college soccer teams based on match results,
# taking into account base overalls, match outcomes, opponent strength, and goal differences.
# It displays the team record (Wins-Draws-Losses) when printing the results.
# Each team is part of one division declared at the beginning (ACC, B1G, B12, SEC, MW, or BDIV).
# Each division causes the team name to be a specific color in the print statement at the end.

# ================== Input Section ==================

# Import colorama for colored output
import colorama
from colorama import Fore, Style
colorama.init(autoreset=True)

# Define divisions
team_divisions = {
    # ACC Teams
    'Miami FL': 'ACC',
    'Clemson': 'ACC',
    'Louisville': 'ACC',
    'Syracuse': 'ACC',
    'Virginia Tech': 'ACC',
    'Georgia Tech': 'ACC',
    'Pitt': 'ACC',
    'Wake Forest': 'ACC',
    'Boston College': 'ACC',
    'UNC': 'ACC',
    'Virginia': 'ACC',
    'Florida State': 'ACC',
    'NC State': 'ACC',
    'California': 'ACC',
    'Stanford': 'ACC',
    'SMU': 'ACC',
    
    # Big Ten (B1G) Teams
    'Ohio State': 'B1G',
    'Michigan': 'B1G',
    'Michigan State': 'B1G',
    'Penn State': 'B1G',
    'Wisconsin': 'B1G',
    'Iowa': 'B1G',
    'Illinois': 'B1G',
    'Northwestern': 'B1G',
    'Minnesota': 'B1G',
    'Indiana': 'B1G',
    'Rutgers': 'B1G',
    'Maryland': 'B1G',
    'Nebraska': 'B1G',
    'UCLA': 'B1G',
    'Washington': 'B1G',
    'Oregon': 'B1G',
    'USC': 'B1G',
    
    # Big 12 (B12) Teams
    'Colorado': 'B12',
    'Utah': 'B12',
    'Kansas': 'B12',
    'Houston': 'B12',
    'Kansas State': 'B12',
    'Iowa State': 'B12',
    'Texas Tech': 'B12',
    'Central Florida': 'B12',
    'TCU': 'B12',
    'Baylor': 'B12',
    'West Virginia': 'B12',
    'Brigham Young': 'B12',
    'Tulane': 'B12',
    'Army': 'B12',
    'Arizona': 'B12',
    'Arizona State': 'B12',
    'Rice': 'B12',
    
    # SEC Teams
    'Oklahoma': 'SEC',
    'Texas': 'SEC',
    'Alabama': 'SEC',
    'LSU': 'SEC',
    'Georgia': 'SEC',
    'Florida': 'SEC',
    'Auburn': 'SEC',
    'Tennessee': 'SEC',
    'Ole Miss': 'SEC',
    'Texas A&M': 'SEC',
    'Arkansas': 'SEC',
    'Vanderbilt': 'SEC',
    'South Carolina': 'SEC',
    'MS State': 'SEC',
    'Kentucky': 'SEC',
    'Missouri': 'SEC',
    'Louisiana': 'SEC',
    
    # Mountain West (MW) Teams
    'Oklahoma State': 'MW',
    'Boise State': 'MW',
    'San Diego State': 'MW',
    'Wyoming': 'MW',
    'CO State': 'MW',
    'Air Force': 'MW',
    'Hawaii': 'MW',
    'Utah State': 'MW',
    'Nevada': 'MW',
    'SJSU': 'MW',
    'Wash St': 'MW',
    'Notre Dame': 'MW',
    'Oregon State': 'MW',
    'Cincinnati': 'MW',
    'UMass': 'MW',
    'UConn': 'MW',
    'WKU': 'MW',

    # BDIV: Other Divisions (Teams not in above divisions)
    'Idaho': 'BDIV',
    'Old Dominion': 'BDIV',
    'Coastal Carolina': 'BDIV',
    'Holy Cross': 'BDIV',
    'UC Davis': 'BDIV',
    'GA Southern': 'BDIV',
    'Middle Tenn': 'BDIV',
    'App State': 'BDIV',
    'Fordham': 'BDIV',
    'MO State': 'BDIV',
    'Villanova': 'BDIV',
    'Indiana State': 'BDIV',
    'Purdue': 'BDIV',
    'Troy': 'BDIV',
    'Morehead State': 'BDIV',
    'Bucknell': 'BDIV',
    'GA State': 'BDIV',
    'Northern CO': 'BDIV',
}

# Assign 'BDIV' to teams not in divisions
teams_overall = {
    'Arizona State': 67,
    'Miami FL': 91,
    'SMU': 88,
    'Virginia Tech': 75,
    'Louisville': 72,
    'Clemson': 81,
    'Georgia Tech': 67,
    'Syracuse': 55,
    'Pitt': 73,
    'Wake Forest': 65,
    'NC State': 62,
    'Stanford': 56,
    'Boston College': 67,
    'Virginia': 51,
    'California': 61,
    'Florida State': 55,
    'UNC': 50,
    'Houston': 65,
    'Central Florida': 56,
    'Texas Tech': 60,
    'Baylor': 58,
    'Iowa State': 69,
    'Kansas': 61,
    'West Virginia': 72,
    'Brigham Young': 67,
    'Tulane': 60,
    'Kansas State': 64,
    'Utah': 61,
    'Rice': 46,
    'Army': 74,
    'Arizona': 59,
    'TCU': 66,
    'Colorado': 76,
    'Illinois': 76,
    'Northwestern': 59,
    'Penn State': 87,
    'Oregon': 92,
    'Indiana': 73,
    'Minnesota': 79,
    'USC': 65,
    'Iowa': 72,
    'Rutgers': 72,
    'Wisconsin': 73,
    'Michigan': 70,
    'Nebraska': 74,
    'Washington': 75,
    'UCLA': 58,
    'Ohio State': 83,
    'Michigan State': 57,
    'Maryland': 56,
    'Texas A&M': 80,
    'Ole Miss': 80,
    'Alabama': 80,
    'Tennessee': 82,
    'Louisiana': 54,
    'LSU': 73,
    'Auburn': 62,
    'Georgia': 89,
    'Arkansas': 76,
    'MS State': 54,
    'Vanderbilt': 69,
    'Kentucky': 59,
    'Florida': 63,
    'South Carolina': 68,
    'Oklahoma': 48,
    'Texas': 78,
    'Missouri': 67,
    'UMass': 59,
    'Hawaii': 62,
    'Wash St': 73,
    'Cincinnati': 67,
    'Boise State': 77,
    'Oklahoma State': 55,
    'CO State': 69,
    'Oregon State': 66,
    'Air Force': 51,
    'WKU': 51,
    'Utah State': 56,
    'San Diego State': 66,
    'UConn': 65,
    'Notre Dame': 72,
    'SJSU': 63,
    'Wyoming': 58,
    'Nevada': 55,
    'App State': 55,
    'Indiana State': 40,
    'Middle Tenn': 53,
    'Idaho': 54,
    'MO State': 53,
    'Old Dominion': 58,
    'Fordham': 44,
    'Coastal Carolina': 57,
    'GA State': 48,
    'Purdue': 57,
    'GA Southern': 60,
    'Villanova': 51,
    'Northern CO': 36,
    'Troy': 48,
    'UC Davis': 54,
    'Holy Cross': 50,
    'Bucknell': 48,
    'Morehead State': 47
}

for team in teams_overall.keys():
    if team not in team_divisions:
        team_divisions[team] = 'BDIV'

# Define colors for each division
division_colors = {
    'ACC': Fore.RED,
    'B1G': Fore.GREEN,
    'B12': Fore.YELLOW,
    'SEC': Fore.BLUE,
    'MW': Fore.MAGENTA,
    'BDIV': Fore.CYAN
}

# Enter the match results in bulk.
# Each match is represented as a tuple:
# (Team A, Team B, Team A goals scored, Team B goals scored)

match_results = [
   ('SMU', 'UNC', 3, 0),
    ('Stanford', 'Virginia Tech', 0, 2),
    ('NC State', 'Clemson', 1, 2),
    ('Louisville', 'Pitt', 1, 0),
    ('Syracuse', 'Boston College', 3, 1),
    ('Miami FL', 'Virginia', 3, 0),
    ('Wake Forest', 'Florida State', 0, 0),
    ('Georgia Tech', 'California', 1, 1),
    ('Houston', 'Central Florida', 4, 0),
    ('Texas Tech', 'Arizona State', 3, 2),
    ('Tulane', 'West Virginia', 1, 1),
    ('Colorado', 'TCU', 5, 2),
    ('Kansas', 'Iowa State', 2, 2),
    ('Baylor', 'Arizona', 1, 0),
    ('Kansas State', 'Rice', 1, 1),
    ('Brigham Young', 'Utah', 1, 1),
    ('Washington', 'Penn State', 2, 3),
    ('USC', 'Minnesota', 2, 2),
    ('Rutgers', 'Iowa', 1, 1),
    ('Wisconsin', 'Michigan', 0, 0),
    ('Michigan State', 'Northwestern', 0, 2),
    ('Maryland', 'Illinois', 0, 4),
    ('Oregon', 'UCLA', 2, 1),
    ('Indiana', 'Ohio State', 1, 0),
    ('Auburn', 'Oklahoma', 1, 0),
    ('Texas A&M', 'Texas', 3, 1),
    ('Vanderbilt', 'Tennessee', 1, 1),
    ('Arkansas', 'Georgia', 1, 1),
    ('Louisiana', 'Kentucky', 2, 1),
    ('Alabama', 'Florida', 2, 1),
    ('South Carolina', 'LSU', 0, 1),
    ('Ole Miss', 'Missouri', 3, 1),
    ('UConn', 'Oklahoma State', 0, 1),
    ('UMass', 'Nevada', 4, 1),
    ('Notre Dame', 'Boise State', 0, 1),
    ('Cincinnati', 'San Diego State', 2, 1),
    ('Hawaii', 'Wyoming', 2, 0),
    ('CO State', 'Oregon State', 1, 1),
    ('Wash St', 'SJSU', 2, 0),
    ('Air Force', 'WKU', 1, 1),
    ('Morehead State', 'App State', 1, 5),
    ('GA State', 'Coastal Carolina', 1, 1),
    ('Fordham', 'GA Southern', 1, 1),
    ('Villanova', 'Purdue', 1, 1),
    ('Old Dominion', 'Northern CO', 2, 0),
    ('UC Davis', 'Idaho', 1, 2),
    ('Middle Tenn', 'Bucknell', 3, 1),
    ('Troy', 'MO State', 1, 2),
    ('Indiana State', 'Holy Cross', 5, 3),

    ('Virginia Tech', 'SMU', 1, 3),
    ('Clemson', 'UNC', 1, 0),
    ('Pitt', 'Stanford', 2, 1),
    ('Boston College', 'NC State', 1, 0),
    ('Virginia', 'Louisville', 0, 2),
    ('Florida State', 'Syracuse', 0, 2),
    ('California', 'Miami FL', 0, 3),
    ('Georgia Tech', 'Wake Forest', 2, 1),
    ('Arizona State', 'Army', 4, 1),
    ('West Virginia', 'Houston', 1, 1),
    ('TCU', 'Texas Tech', 1, 1),
    ('Iowa State', 'Tulane', 6, 1),
    ('Arizona', 'Colorado', 1, 1),
    ('Rice', 'Kansas', 1, 1),
    ('Utah', 'Baylor', 2, 0),
    ('Brigham Young', 'Kansas State', 1, 1),
    ('Minnesota', 'Nebraska', 3, 1),
    ('Iowa', 'Washington', 1, 1),
    ('Michigan', 'USC', 3, 0),
    ('Northwestern', 'Rutgers', 2, 1),
    ('Illinois', 'Wisconsin', 2, 1),
    ('UCLA', 'Michigan State', 1, 1),
    ('Ohio State', 'Maryland', 2, 1),
    ('Indiana', 'Oregon', 0, 0),
    ('Texas', 'MS State', 0, 0),
    ('Tennessee', 'Auburn', 1, 0),
    ('Georgia', 'Texas A&M', 1, 0),
    ('Kentucky', 'Vanderbilt', 1, 1),
    ('Florida', 'Arkansas', 1, 4),
    ('LSU', 'Louisiana', 2, 1),
    ('Missouri', 'Alabama', 0, 3),
    ('Ole Miss', 'South Carolina', 4, 0),
    ('Nevada', 'Utah State', 0, 0),
    ('Boise State', 'UConn', 1, 0),
    ('San Diego State', 'UMass', 0, 1),
    ('Wyoming', 'Notre Dame', 1, 0),
    ('Oregon State', 'Cincinnati', 1, 0),
    ('SJSU', 'Hawaii', 1, 0),
    ('WKU', 'CO State', 1, 3),
    ('Air Force', 'Wash St', 2, 3),
    ('Coastal Carolina', 'Morehead State', 2, 1),
    ('GA Southern', 'App State', 1, 1),
    ('Purdue', 'GA State', 1, 1),
    ('Northern CO', 'Fordham', 1, 1),
    ('Idaho', 'Villanova', 0, 0),
    ('Bucknell', 'Old Dominion', 1, 1),
    ('MO State', 'UC Davis', 0, 2),
    ('Holy Cross', 'Middle Tenn', 3, 1),
    ('Indiana State', 'Troy', 1, 2),
    
    ('SMU', 'Clemson', 0, 1),
    ('Virginia Tech', 'Pitt', 1, 0),
    ('UNC', 'Boston College', 1, 1),
    ('Stanford', 'Virginia', 3, 1),
    ('NC State', 'Florida State', 2, 0),
    ('Louisville', 'California', 1, 1),
    ('Syracuse', 'Georgia Tech', 4, 3),
    ('Miami FL', 'Wake Forest', 0, 0),
    ('Central Florida', 'West Virginia', 0, 1),
    ('Army', 'TCU', 2, 0),
    ('Houston', 'Iowa State', 1, 1),
    ('Texas Tech', 'Arizona', 1, 0),
    ('Tulane', 'Rice', 3, 0),
    ('Colorado', 'Utah', 2, 0),
    ('Kansas', 'Brigham Young', 1, 1),
    ('Baylor', 'Kansas State', 3, 4),
    ('Penn State', 'Iowa', 3, 0),
    ('Nebraska', 'Michigan', 1, 3),
    ('Washington', 'Northwestern', 3, 0),
    ('USC', 'Illinois', 1, 1),
    ('Rutgers', 'UCLA', 4, 0),
    ('Wisconsin', 'Ohio State', 0, 2),
    ('Michigan State', 'Indiana', 1, 1),
    ('Maryland', 'Oregon', 0, 2),
    ('Oklahoma', 'Tennessee', 0, 5),
    ('MS State', 'Georgia', 0, 2),
    ('Auburn', 'Kentucky', 3, 1),
    ('Texas A&M', 'Florida', 2, 1),
    ('Vanderbilt', 'LSU', 1, 2),
    ('Arkansas', 'Missouri', 1, 2),
    ('Louisiana', 'Ole Miss', 1, 4),
    ('Alabama', 'South Carolina', 1, 1),
    ('Oklahoma State', 'Boise State', 0, 2),
    ('Utah State', 'San Diego State', 1, 1),
    ('UConn', 'Wyoming', 0, 0),
    ('UMass', 'Oregon State', 1, 2),
    ('Notre Dame', 'SJSU', 2, 1),
    ('Cincinnati', 'WKU', 4, 0),
    ('Hawaii', 'Air Force', 1, 1),
    ('CO State', 'Wash St', 0, 1),
    ('Morehead State', 'GA Southern', 0, 1),
    ('Coastal Carolina', 'Purdue', 3, 0),
    ('App State', 'Northern CO', 3, 0),
    ('GA State', 'Idaho', 0, 3),
    ('Fordham', 'Bucknell', 2, 2),
    ('Villanova', 'MO State', 2, 0),
    ('Old Dominion', 'Holy Cross', 2, 4),
    ('UC Davis', 'Indiana State', 1, 3),
    ('Middle Tenn', 'Troy', 3, 2),
    
    ('Pitt', 'SMU', 0, 6),
    ('Boston College', 'Clemson', 2, 2),
    ('Virginia', 'Virginia Tech', 0, 0),
    ('Florida State', 'UNC', 2, 1),
    ('California', 'Stanford', 2, 1),
    ('Georgia Tech', 'NC State', 2, 3),
    ('Wake Forest', 'Louisville', 2, 1),
    ('Miami FL', 'Syracuse', 3, 0),
    ('TCU', 'Arizona State', 1, 0),
    ('Iowa State', 'Central Florida', 3, 0),
    ('Arizona', 'Army', 1, 2),
    ('Rice', 'Houston', 0, 1),
    ('Utah', 'Texas Tech', 2, 1),
    ('Brigham Young', 'Tulane', 3, 0),
    ('Kansas State', 'Colorado', 2, 1),
    ('Baylor', 'Kansas', 2, 1),
    ('Michigan', 'Minnesota', 1, 2),
    ('Northwestern', 'Penn State', 0, 2),
    ('Illinois', 'Nebraska', 1, 1),
    ('UCLA', 'Washington', 3, 0),
    ('Ohio State', 'USC', 1, 0),
    ('Indiana', 'Rutgers', 1, 2),
    ('Oregon', 'Wisconsin', 4, 0),
    ('Maryland', 'Michigan State', 4, 3),
    ('Georgia', 'Texas', 2, 2),
    ('Kentucky', 'Oklahoma', 2, 1),
    ('Florida', 'MS State', 0, 0),
    ('LSU', 'Auburn', 2, 1),
    ('Missouri', 'Texas A&M', 1, 1),
    ('Ole Miss', 'Vanderbilt', 3, 0),
    ('South Carolina', 'Arkansas', 4, 3),
    ('Alabama', 'Louisiana', 3, 1),
    ('San Diego State', 'Nevada', 2, 2),
    ('Wyoming', 'Oklahoma State', 1, 2),
    ('Oregon State', 'Utah State', 4, 0),
    ('SJSU', 'UConn', 0, 0),
    ('WKU', 'UMass', 0, 1),
    ('Air Force', 'Notre Dame', 0, 1),
    ('Wash St', 'Cincinnati', 1, 0),
    ('CO State', 'Hawaii', 0, 0),
    ('Purdue', 'Morehead State', 1, 1),
    ('Northern CO', 'GA Southern', 0, 2),
    ('Idaho', 'Coastal Carolina', 1, 1),
    ('Bucknell', 'App State', 2, 0),
    ('MO State', 'GA State', 3, 0),
    ('Holy Cross', 'Fordham', 1, 0),
    ('Indiana State', 'Villanova', 1, 3),
    ('Troy', 'Old Dominion', 0, 2),
    ('Middle Tenn', 'UC Davis', 0, 0),
    
    ('SMU', 'Boston College', 2, 1),
    ('Pitt', 'Virginia', 0, 0),
    ('Clemson', 'Florida State', 5, 0),
    ('Virginia Tech', 'California', 3, 0),
    ('UNC', 'Georgia Tech', 2, 2),
    ('Stanford', 'Wake Forest', 2, 1),
    ('NC State', 'Miami FL', 0, 2),
    ('Louisville', 'Syracuse', 4, 1),
    ('West Virginia', 'Iowa State', 4, 0),
    ('Arizona State', 'Arizona', 2, 1),
    ('Central Florida', 'Rice', 1, 0),
    ('Army', 'Utah', 1, 3),
    ('Houston', 'Brigham Young', 0, 0),
    ('Texas Tech', 'Kansas State', 0, 2),
    ('Tulane', 'Baylor', 3, 1),
    ('Colorado', 'Kansas', 3, 1),
    ('Iowa', 'Northwestern', 1, 1),
    ('Minnesota', 'Illinois', 0, 1),
    ('Penn State', 'UCLA', 3, 0),
    ('Nebraska', 'Ohio State', 3, 3),
    ('Washington', 'Indiana', 1, 4),
    ('USC', 'Oregon', 1, 2),
    ('Rutgers', 'Maryland', 2, 2),
    ('Wisconsin', 'Michigan State', 2, 0),
    ('Tennessee', 'Kentucky', 2, 1),
    ('Texas', 'Florida', 0, 0),
    ('Oklahoma', 'LSU', 0, 1),
    ('MS State', 'Missouri', 3, 1),
    ('Auburn', 'Ole Miss', 3, 2),
    ('Texas A&M', 'South Carolina', 1, 0),
    ('Vanderbilt', 'Alabama', 0, 1),
    ('Arkansas', 'Louisiana', 2, 0),
    ('Boise State', 'Wyoming', 2, 2),
    ('Nevada', 'Oregon State', 0, 4),
    ('Oklahoma State', 'SJSU', 0, 1),
    ('Utah State', 'WKU', 1, 2),
    ('UConn', 'Air Force', 3, 0),
    ('UMass', 'Wash St', 2, 5),
    ('Notre Dame', 'CO State', 1, 0),
    ('Cincinnati', 'Hawaii', 1, 1),
    ('Morehead State', 'Northern CO', 4, 0),
    ('Purdue', 'Idaho', 3, 1),
    ('GA Southern', 'Bucknell', 2, 0),
    ('Coastal Carolina', 'MO State', 2, 1),
    ('App State', 'Holy Cross', 0, 0),
    ('GA State', 'Indiana State', 3, 0),
    ('Fordham', 'Troy', 0, 0),
    ('Villanova', 'Middle Tenn', 1, 3),
    ('Old Dominion', 'UC Davis', 0, 2),
    
    ('Virginia', 'SMU', 2, 2),
    ('Florida State', 'Boston College', 0, 1),
    ('California', 'Pitt', 1, 2),
    ('Georgia Tech', 'Clemson', 3, 1),
    ('Wake Forest', 'Virginia Tech', 1, 3),
    ('Miami FL', 'UNC', 2, 0),
    ('Syracuse', 'Stanford', 2, 0),
    ('Louisville', 'NC State', 2, 0),
    ('Arizona', 'TCU', 2, 1),
    ('Rice', 'West Virginia', 0, 2),
    ('Utah', 'Arizona State', 2, 0),
    ('Brigham Young', 'Central Florida', 0, 0),
    ('Kansas State', 'Army', 2, 2),
    ('Baylor', 'Houston', 0, 1),
    ('Kansas', 'Texas Tech', 2, 2),
    ('Colorado', 'Tulane', 2, 0),
    ('Illinois', 'Michigan', 1, 1),
    ('UCLA', 'Iowa', 1, 1),
    ('Ohio State', 'Minnesota', 2, 0),
    ('Indiana', 'Penn State', 0, 0),
    ('Oregon', 'Nebraska', 2, 0),
    ('Maryland', 'Washington', 0, 2),
    ('Michigan State', 'USC', 1, 4),
    ('Wisconsin', 'Rutgers', 3, 1),
    ('Florida', 'Georgia', 0, 5),
    ('LSU', 'Tennessee', 0, 1),
    ('Missouri', 'Texas', 1, 3),
    ('Ole Miss', 'Oklahoma', 4, 0),
    ('South Carolina', 'MS State', 0, 1),
    ('Alabama', 'Auburn', 1, 0),
    ('Louisiana', 'Texas A&M', 0, 1),
    ('Arkansas', 'Vanderbilt', 2, 0),
    ('Oregon State', 'San Diego State', 1, 4),
    ('SJSU', 'Boise State', 0, 0),
    ('WKU', 'Nevada', 1, 3),
    ('Air Force', 'Oklahoma State', 2, 2),
    ('Wash St', 'Utah State', 4, 1),
    ('CO State', 'UConn', 2, 1),
    ('Hawaii', 'UMass', 3, 1),
    ('Cincinnati', 'Notre Dame', 1, 3),
    ('Idaho', 'Morehead State', 2, 1),
    ('Bucknell', 'Northern CO', 1, 1),
    ('MO State', 'Purdue', 1, 1),
    ('Holy Cross', 'GA Southern', 1, 2),
    ('Indiana State', 'Coastal Carolina', 0, 0),
    ('Troy', 'App State', 0, 1),
    ('Middle Tenn', 'GA State', 1, 0),
    ('UC Davis', 'Fordham', 4, 0),
    ('Old Dominion', 'Villanova', 2, 0),
    
    ('SMU', 'Florida State', 6, 0),
    ('Virginia', 'California', 3, 2),
    ('Boston College', 'Georgia Tech', 2, 3),
    ('Pitt', 'Wake Forest', 4, 4),
    ('Clemson', 'Miami FL', 1, 3),
    ('Virginia Tech', 'Syracuse', 4, 0),
    ('UNC', 'Louisville', 1, 2),
    ('Stanford', 'NC State', 0, 4),
    ('Iowa State', 'Rice', 2, 2),
    ('TCU', 'Utah', 2, 2),
    ('West Virginia', 'Brigham Young', 2, 0),
    ('Arizona State', 'Kansas State', 0, 2),
    ('Central Florida', 'Baylor', 4, 2),
    ('Army', 'Kansas', 2, 2),
    ('Houston', 'Colorado', 1, 1),
    ('Texas Tech', 'Tulane', 2, 1),
    ('Northwestern', 'UCLA', 0, 0),
    ('Michigan', 'Ohio State', 3, 2),
    ('Iowa', 'Indiana', 0, 2),
    ('Minnesota', 'Oregon', 1, 2),
    ('Penn State', 'Maryland', 4, 0),
    ('Nebraska', 'Michigan State', 2, 0),
    ('Washington', 'Wisconsin', 2, 2),
    ('USC', 'Rutgers', 1, 0),
    ('Kentucky', 'LSU', 3, 3),
    ('Georgia', 'Missouri', 3, 0),
    ('Tennessee', 'Ole Miss', 1, 2),
    ('Texas', 'South Carolina', 2, 0),
    ('Oklahoma', 'Alabama', 0, 0),
    ('MS State', 'Louisiana', 3, 3),
    ('Auburn', 'Arkansas', 0, 2),
    ('Texas A&M', 'Vanderbilt', 3, 2),
    ('Wyoming', 'SJSU', 0, 4),
    ('San Diego State', 'WKU', 3, 0),
    ('Boise State', 'Air Force', 3, 0),
    ('Nevada', 'Wash St', 0, 1),
    ('Oklahoma State', 'CO State', 1, 3),
    ('Utah State', 'Hawaii', 2, 0),
    ('UConn', 'Cincinnati', 2, 4),
    ('UMass', 'Notre Dame', 0, 1),
    ('Morehead State', 'Bucknell', 2, 0),
    ('Idaho', 'MO State', 2, 0),
    ('Northern CO', 'Holy Cross', 1, 2),
    ('Purdue', 'Indiana State', 0, 0),
    ('GA Southern', 'Troy', 0, 1),
    ('Coastal Carolina', 'Middle Tenn', 4, 0),
    ('App State', 'UC Davis', 1, 1),
    ('GA State', 'Old Dominion', 0, 2),
    ('Fordham', 'Villanova', 2, 1),
    
    ('California', 'SMU', 0, 2),
    ('Georgia Tech', 'Florida State', 2, 2),
    ('Wake Forest', 'Virginia', 5, 0),
    ('Miami FL', 'Boston College', 2, 0),
    ('Syracuse', 'Pitt', 1, 3),
    ('Louisville', 'Clemson', 0, 1),
    ('NC State', 'Virginia Tech', 1, 2),
    ('Stanford', 'UNC', 5, 2),
    ('Utah', 'Arizona', 1, 2),
    ('Brigham Young', 'Iowa State', 0, 0),
    ('Kansas State', 'TCU', 1, 5),
    ('Baylor', 'West Virginia', 1, 4),
    ('Kansas', 'Arizona State', 2, 0),
    ('Colorado', 'Central Florida', 0, 1),
    ('Tulane', 'Army', 1, 1),
    ('Texas Tech', 'Houston', 3, 2),
    ('Ohio State', 'Illinois', 2, 1),
    ('Indiana', 'Northwestern', 2, 1),
    ('Oregon', 'Michigan', 3, 1),
    ('Maryland', 'Iowa', 1, 1),
    ('Michigan State', 'Minnesota', 0, 1),
    ('Wisconsin', 'Penn State', 0, 3),
    ('Rutgers', 'Nebraska', 1, 1),
    ('USC', 'Washington', 0, 1),
    ('Missouri', 'Florida', 2, 1),
    ('Ole Miss', 'Kentucky', 1, 0),
    ('South Carolina', 'Georgia', 0, 4),
    ('Alabama', 'Tennessee', 2, 1),
    ('Louisiana', 'Texas', 0, 2),
    ('Arkansas', 'Oklahoma', 5, 0),
    ('Vanderbilt', 'MS State', 2, 1),
    ('Texas A&M', 'Auburn', 0, 0),
    ('WKU', 'Oregon State', 0, 2),
    ('Air Force', 'Wyoming', 5, 4),
    ('Wash St', 'San Diego State', 0, 1),
    ('CO State', 'Boise State', 3, 0),
    ('Hawaii', 'Nevada', 2, 0),
    ('Cincinnati', 'Oklahoma State', 1, 0),
    ('Notre Dame', 'Utah State', 3, 2),
    ('UMass', 'UConn', 2, 3),
    ('MO State', 'Morehead State', 3, 0),
    ('Holy Cross', 'Bucknell', 2, 0),
    ('Indiana State', 'Idaho', 1, 2),
    ('Troy', 'Northern CO', 1, 1),
    ('Middle Tenn', 'Purdue', 1, 1),
    ('UC Davis', 'GA Southern', 2, 1),
    ('Old Dominion', 'Coastal Carolina', 3, 0),
    ('Villanova', 'App State', 2, 2),
    ('Fordham', 'GA State', 6, 2),
    
    ('SMU', 'Georgia Tech', 2, 0),
    ('California', 'Wake Forest', 3, 2),
    ('Florida State', 'Miami FL', 0, 4),
    ('Virginia', 'Syracuse', 0, 2),
    ('Boston College', 'Louisville', 0, 0),
    ('Pitt', 'NC State', 1, 2),
    ('Clemson', 'Stanford', 4, 0),
    ('Virginia Tech', 'UNC', 3, 0),
    ('Rice', 'Brigham Young', 0, 3),
    ('Arizona', 'Kansas State', 1, 2),
    ('Iowa State', 'Baylor', 4, 0),
    ('TCU', 'Kansas', 3, 0),
    ('West Virginia', 'Colorado', 0, 1),
    ('Arizona State', 'Tulane', 3, 0),
    ('Central Florida', 'Texas Tech', 0, 4),
    ('Army', 'Houston', 2, 0),
    ('UCLA', 'Indiana', 2, 4),
    ('Illinois', 'Oregon', 1, 1),
    ('Northwestern', 'Maryland', 3, 0),
    ('Michigan', 'Michigan State', 2, 0),
    ('Iowa', 'Wisconsin', 2, 1),
    ('Minnesota', 'Rutgers', 0, 2),
    ('Penn State', 'USC', 4, 0),
    ('Nebraska', 'Washington', 1, 3),
    ('LSU', 'Ole Miss', 2, 0),
    ('Florida', 'South Carolina', 1, 2),
    ('Kentucky', 'Alabama', 0, 4),
    ('Georgia', 'Louisiana', 3, 0),
    ('Tennessee', 'Arkansas', 2, 0),
    ('Texas', 'Vanderbilt', 2, 1),
    ('Oklahoma', 'Texas A&M', 1, 3),
    ('MS State', 'Auburn', 1, 1),
    ('SJSU', 'Air Force', 3, 0),
    ('Oregon State', 'Wash St', 2, 1),
    ('Wyoming', 'CO State', 1, 3),
    ('San Diego State', 'Hawaii', 3, 2),
    ('Boise State', 'Cincinnati', 1, 0),
    ('Nevada', 'Notre Dame', 1, 0),
    ('Oklahoma State', 'UMass', 0, 0),
    ('Utah State', 'UConn', 1, 1),
    ('Morehead State', 'Holy Cross', 1, 2),
    ('MO State', 'Indiana State', 3, 0),
    ('Bucknell', 'Troy', 3, 0),
    ('Idaho', 'Middle Tenn', 0, 1),
    ('Northern CO', 'UC Davis', 1, 3),
    ('Purdue', 'Old Dominion', 2, 1),
    ('GA Southern', 'Villanova', 1, 2),
    ('Coastal Carolina', 'Fordham', 2, 2),
    ('App State', 'GA State', 2, 1),

    ('Wake Forest', 'SMU', 1, 3),
    ('Miami FL', 'Georgia Tech', 1, 0),
    ('Syracuse', 'California', 1, 2),
    ('Louisville', 'Florida State', 1, 0),
    ('NC State', 'Virginia', 2, 1),
    ('Stanford', 'Boston College', 0, 3),
    ('UNC', 'Pitt', 1, 2),
    ('Virginia Tech', 'Clemson', 1, 2)
]

# ================== Program Code ==================

# Initialize team data
teams = {}
for team, overall in teams_overall.items():
    teams[team] = {
        'total_points': 0,
        'games_played': 0,
        'wins': 0,
        'draws': 0,
        'losses': 0,
        'base_overall': overall
    }

average_overall = sum(teams_overall.values()) / len(teams_overall)

# Process each match
for match in match_results:
    team_a, team_b, goals_a, goals_b = match
    overall_a = teams[team_a]['base_overall']
    overall_b = teams[team_b]['base_overall']

    # Update games played
    teams[team_a]['games_played'] += 1
    teams[team_b]['games_played'] += 1

    # Basic match points
    if goals_a > goals_b:
        # Team A wins
        result_points_a = 3
        result_points_b = 0
        teams[team_a]['wins'] += 1
        teams[team_b]['losses'] += 1
    elif goals_a == goals_b:
        # Draw
        result_points_a = 1
        result_points_b = 1
        teams[team_a]['draws'] += 1
        teams[team_b]['draws'] += 1
    else:
        # Team B wins
        result_points_a = 0
        result_points_b = 3
        teams[team_b]['wins'] += 1
        teams[team_a]['losses'] += 1

    # Opponent strength factor
    strength_factor_a = overall_b / average_overall
    strength_factor_b = overall_a / average_overall

    # Goal difference factor
    goal_diff = abs(goals_a - goals_b)
    goal_diff_bonus = goal_diff * 0.1  # Adjust this factor as needed

    # Calculate total points for each team
    points_a = (result_points_a * strength_factor_a) + goal_diff_bonus
    points_b = (result_points_b * strength_factor_b) + goal_diff_bonus

    # Small influence of team's own overall
    own_overall_factor = 0.05  # Adjust this factor as needed
    points_a += own_overall_factor * overall_a
    points_b += own_overall_factor * overall_b

    # Update total points
    teams[team_a]['total_points'] += points_a
    teams[team_b]['total_points'] += points_b

# Calculate average points per game
for team in teams.keys():
    games_played = teams[team]['games_played']
    if games_played > 0:
        teams[team]['avg_points'] = teams[team]['total_points'] / games_played
    else:
        teams[team]['avg_points'] = 0

# Generate rankings
rankings = sorted(teams.items(), key=lambda item: item[1]['avg_points'], reverse=True)

# ================== Output Section ==================

print("College Soccer Teams Rankings:")
header = "{:<5} {:<15} {:<15} {:<15} {:<10}".format('Rank', 'Team', 'Avg Points', 'Record', 'Games Played')
print(header)
print('-' * len(header))
for idx, (team, data) in enumerate(rankings, 1):
    record = f"{data['wins']}-{data['draws']}-{data['losses']}"
    division = team_divisions.get(team, 'BDIV')
    color = division_colors.get(division, Fore.WHITE)
    team_name_colored = f"{color}{team}{Style.RESET_ALL}"
    print("{:<5} {:<25} {:<15.2f} {:<15} {:<10}".format(
        idx, team_name_colored, data['avg_points'], record, data['games_played']
    ))
